<?php $this->parentTemplate('/admin/layout.phtml'); ?>

<?php $this->block('content'); ?>

<div class="content">

    <h2 class="icon user">Nutzer anlegen</h2>

    <hr class="invisible" />

    <?php /** @var \Faulancer\Form\AbstractFormBuilder $form  */ ?>
    <?= $form->getFormOpen(); ?>

    <div class="container width-100">

        <div class="row">
            <div class="cell"><?= $form->getField('gender')->getLabel(); ?></div>
            <div class="cell">
                <?= $form->getField('gender'); ?>
                <?= $form->getField('gender')->getErrorMessage(); ?>
            </div>
        </div>
        <div class="row">
            <div class="cell"><?= $form->getField('firstname')->getLabel(); ?></div>
            <div class="cell">
                <?= $form->getField('firstname'); ?>
                <?= $form->getField('firstname')->getErrorMessage(); ?>
            </div>
        </div>
        <div class="row">
            <div class="cell"><?= $form->getField('lastname')->getLabel(); ?></div>
            <div class="cell">
                <?= $form->getField('lastname'); ?>
                <?= $form->getField('lastname')->getErrorMessage(); ?>
            </div>
        </div>
        <div class="row">
            <div class="cell"><?= $form->getField('isAdmin')->getLabel(); ?></div>
            <div class="cell">
                <?= $form->getField('isAdmin'); ?>
                <?= $form->getField('isAdmin')->getErrorMessage(); ?>
            </div>
        </div>

        <div class="row">
            <div class="cell"><?= $form->getField('radioButton')->getLabel(); ?></div>
            <div class="cell">
                <?= $form->getField('radioButton')->getOption('option1'); ?>
                <?= $form->getField('radioButton')->getOption('option2'); ?>
                <?= $form->getField('radioButton')->getErrorMessage(); ?>
            </div>
        </div>

    </div>

    <?= $form->getField('submit'); ?>

    <?= $form->getFormClose(); ?>

</div>



<?php $this->endBlock('content'); ?>
