<?php $this->parentTemplate('/admin/layout.phtml'); ?>

<?php $this->block('content'); ?>

<div class="content">

    <h2 class="icon user">Nutzer editieren</h2>

    <hr class="invisible" />

    <form action="/formrequest/userEdit" method="POST">

        <div class="container width-100">
            <div class="row">
                <div class="cell width-15"><label for="gender">Anrede:</label></div>
                <div class="cell">
                    <?php $gender = $this->formData('text/gender'); ?>
                    <select id="gender" name="text/gender">
                        <option value="">Bitte wählen</option>
                        <option value="frau"<?= ($gender === 'frau' || $user->gender === 'frau' ? ' selected="selected"' : ''); ?>>Frau</option>
                        <option value="herr"<?= ($gender === 'herr' || $user->gender === 'herr' ? ' selected="selected"' : ''); ?>>Herr</option>
                    </select>
                </div>
            </div>
            <div class="row">
                <div class="cell"><label for="firstname">Vorname:</label></div>
                <div class="cell">
                    <input id="firstname" type="text" name="text/firstname" value="<?= $this->formData('text/firstname') ?: $user->firstname; ?>" />
                    <?= $this->formError('text/firstname')->get(); ?>
                </div>
            </div>
            <div class="row">
                <div class="cell"><label for="lastname">Nachname:</label></div>
                <div class="cell">
                    <input id="lastname" type="text" name="text/lastname" value="<?= $this->formData('text/lastname') ?: $user->lastname; ?>" />
                    <?= $this->formError('text/lastname')->get(); ?>
                </div>
            </div>
            <div class="row">
                <div class="cell"><label for="email">E-Mail:</label></div>
                <div class="cell">
                    <input id="email" type="text" name="email/email" value="<?= $this->formData('email/email') ?: $user->email; ?>" />
                    <?= $this->formError('email/email')->get(); ?>
                </div>
            </div>

        </div>

        <hr />

        <div class="container width-100">
            <div class="row">
                <div class="cell width-15"><label for="login">Login:</label></div>
                <div class="cell">
                    <input id="login" type="text" name="text/login" autocomplete="off" value="<?= $this->formData('text/login') ?: $user->login; ?>" />
                    <?= $this->formError('text/login')->get(); ?>
                </div>
            </div>
            <div class="row">
                <div class="cell"><label for="password">Passwort:</label></div>
                <div class="cell">
                    <input id="password" type="password" name="confirm/password" autocomplete="off" />
                    <?= $this->formError('confirm/password')->get(); ?>
                </div>
            </div>
            <div class="row">
                <div class="cell"><label for="password_repeat">Passwort wiederholen:</label></div>
                <div class="cell">
                    <input id="password_repeat" type="password" name="confirm/password_repeat" autocomplete="off" />
                    <?= $this->formError('confirm/password_repeat')->get(); ?>
                </div>
            </div>
        </div>

        <input type="hidden" name="user_id" value="<?= $user->id; ?>" />

        <input type="hidden" name="csrf" value="<?= $this->generateCsrfToken(); ?>" />

        <hr />

        <button>Absenden</button>

    </form>

</div>



<?php $this->endBlock('content'); ?>
