<?php $this->parentTemplate('/admin/layout.phtml'); ?>

<?php $this->block('content'); ?>

<div class="content">

    <h2 class="icon dashboard">Dashboard</h2>

    <hr class="invisible" />

    <div class="container border width-100 stats">
        <div class="row">
            <div class="cell border space width-25 text-center">

                <span class="count">355</span>
                <span class="title">Bilder hochgeladen</span>

            </div>
            <div class="cell border space width-25 text-center">

                <span class="count">2433</span>
                <span class="title">Nutzer verwaltet</span>

            </div>
            <div class="cell border space width-25 text-center">

                <span class="count">255.500</span>
                <span class="title">Downloads insgesamt</span>

            </div>
            <div class="cell border space width-25 text-center">

                <span class="count">155.500</span>
                <span class="title">Kommentare verfasst</span>

            </div>
        </div>
    </div>

</div>



<?php $this->endBlock('content'); ?>
