<?php $this->parentTemplate('/admin/layout.phtml'); ?>

<?php $this->block('content'); ?>

<div class="content">

    <h2 class="icon user">Nutzer verwalten</h2>

    <hr class="invisible" />

    <div class="admin-section-title">
        <div class="left"><h4>Derzeit registrierte Nutzer</h4></div>
        <div class="right"><a class="btn" href="<?= $this->route('admin_user_add'); ?>"><div class="icon add">Nutzer hinzufügen</div></a></div>
        <div class="clear-both"></div>
    </div>

    <div class="container width-100">

        <div class="row fs-08">
            <?php if ($this->user()->isAuthenticated(['administrator'])): ?>
            <div class="cell width-5">Optionen</div>
            <?php endif; ?>
            <div class="cell width-10">Vorname</div>
            <div class="cell width-10">Nachname</div>
            <div class="cell width-10">E-Mail-Adresse</div>
            <div class="cell width-10">Login</div>
            <div class="cell width-10">Angelegt am</div>
        </div>

    <?php

    $i = 0;

    /** @var \Glry\Entity\UserEntity[] $users */
    foreach ($users as $user): ?>

        <div class="row<?= $i % 2 === 0 ? ' even' : ' odd'; ?>">
            <?php if ($this->user()->isAuthenticated(['administrator'])): ?>
            <div class="cell space-5">

                <a href="<?= $this->route('admin_user_edit', [$user->id]); ?>">
                    <div class="icon inline edit"></div>
                </a>
                <a href="<?= $this->route('admin_user_permission', [$user->id]); ?>">
                    <div class="icon inline permission"></div>
                </a>

                <a href="<?= $this->route('admin_user_delete', [$user->id]); ?>">
                    <div class="icon inline remove"></div>
                </a>
            </div>
            <?php endif; ?>
            <div class="cell space-5"><?= $user->firstname; ?></div>
            <div class="cell space-5"><?= $user->lastname; ?></div>
            <div class="cell space-5"><?= $user->email; ?></div>
            <div class="cell space-5"><?= $user->login; ?></div>
            <div class="cell space-5"><?= (new \DateTime($user->created))->format('d.m.Y, H:i'); ?> Uhr</div>
        </div>

        <?php $i++; ?>

    <?php endforeach; ?>
    </div>

</div>



<?php $this->endBlock('content'); ?>
